# RETORNA TODOS OS REGISTROS DE UMA TABELA
SELECT * FROM employees;

# RETORNA COLUNAS ESPECÍFICAS DE TODOS OS REGISTROS DE UMA TABELA
SELECT first_name, last_name FROM employees;

# RETORNA APENAS REGISTROS ESPECÍFICOS (WHERE)
SELECT * FROM employees WHERE employee_id = 1;
SELECT first_name FROM employees WHERE last_name = "Santos";
SELECT * FROM employees WHERE hourly_pay > 15;
SELECT * FROM employees WHERE employee_id != 1;

# RETORNANDO REGISTRO QUE TEM COLUNA COM VALOR 'NULL'
SELECT * FROM employees WHERE hire_date IS NULL;

# RETORNANDO REGISTRO QUE NÃO TEM COLUNA COM VALOR 'NULL'
SELECT * FROM employees WHERE hire_date IS NOT NULL;